
#include "kernel.h"
#include "console.h"
#include "string.h"
#include "vga.h"

void display_sections() {

    printf("Welcome To ZecelOS! \n");

    //russia

    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);

    console_gotoxy(0, 2);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    pixel(COLOR_BLUE);
    console_gotoxy(0, 3);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);

    //ireland
    console_gotoxy(0, 5);

    pixel(COLOR_GREEN);
    console_gotoxy(0, 6);
    pixel(COLOR_GREEN);
    console_gotoxy(0, 7);
    pixel(COLOR_GREEN);
    console_gotoxy(0, 8);
    pixel(COLOR_GREEN);
    console_gotoxy(0, 9);
    pixel(COLOR_GREEN);
    console_gotoxy(0, 10);
    pixel(COLOR_GREEN);
    console_gotoxy(0, 11);
    pixel(COLOR_GREEN);

    console_gotoxy(1, 5);
    pixel(COLOR_WHITE);
    console_gotoxy(1, 6);
    pixel(COLOR_WHITE);
    console_gotoxy(1, 7);
    pixel(COLOR_WHITE);
    console_gotoxy(1, 8);
    pixel(COLOR_WHITE);
    console_gotoxy(1, 9);
    pixel(COLOR_WHITE);
    console_gotoxy(1, 10);
    pixel(COLOR_WHITE);
    console_gotoxy(1, 11);
    pixel(COLOR_WHITE);

    console_gotoxy(2, 5);
    pixel(COLOR_YELLOW);
    console_gotoxy(2, 6);
    pixel(COLOR_YELLOW);
    console_gotoxy(2, 7);
    pixel(COLOR_YELLOW);
    console_gotoxy(2, 8);
    pixel(COLOR_YELLOW);
    console_gotoxy(2, 9);
    pixel(COLOR_YELLOW);
    console_gotoxy(2, 10);
    pixel(COLOR_YELLOW);
    console_gotoxy(2, 11);
    pixel(COLOR_YELLOW);

    // ENGLANDDDDDDDDDDDDDD

    console_gotoxy(0, 15);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_RED);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    console_gotoxy(0, 16);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_RED);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    console_gotoxy(0, 17);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED); // center
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    pixel(COLOR_RED);
    console_gotoxy(0, 18);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_RED);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    console_gotoxy(0, 19);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_RED);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);
    pixel(COLOR_WHITE);

    rectangle(COLOR_WHITE, 22);

}

void kmain() {
    console_init(COLOR_WHITE, COLOR_BLACK);
    display_sections();
}
